server:
  port: 3002
  servlet:
    context-path: /api
spring:
  application:
    name: teste-pratico-fsbr
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:fsbr
    driverClassName: org.h2.Driver
    username: admin
    password:
  flyway:
    table: schema_version